### ISSUE TITLE
Implement new designs

### ISSUE THREAD

**Issue by edwarddikgale** [aeternity/aepp-blockchain-explorer#109]
parent of #108, parent of #107, parent #106, parent #105, parent #104, parent #103, parent #102, parent #101, parent #100, parent #99, parent #98, parent #97, parent #162, parent #157, parent #156, parent #115

**Comment by edwarddikgale** [comment]
parent of #107

**Comment by ror-shubham** [comment]
Duplicate and outdated tickets
