### ISSUE TITLE
Fix scrolling bug - gets stuck for 100 ms

### ISSUE THREAD

**Issue by edwarddikgale** [aeternity/aepp-blockchain-explorer#119]
child of #110

**Comment by ror-shubham** [comment]
https://github.com/aeternity/aepp-blockchain-explorer/pull/122

**Comment by ror-shubham** [comment]
https://github.com/aeternity/aepp-blockchain-explorer/pull/76

**Comment by ror-shubham** [comment]
Above two PR helps in the issue.

**Comment by artem-rozhkov-dev-optima** [comment]
#133

**Comment by ror-shubham** [comment]
Fixed in #122 and #76
