### ISSUE TITLE
tx summery overlay

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-blockchain-explorer#16]
<img width="785" alt="screen shot 2018-04-16 at 12 09 22" src="https://user-images.githubusercontent.com/415536/38803294-0f0990da-416f-11e8-9299-87acf11672a5.png">
there should be a button to display a tx detail/summery overlay that should slide/fade in the screen

**Comment by kryztoval** [comment]
I like this idea, but the TX endpoint is not done right now, but this sounds really interesting.
