### ISSUE TITLE
Fix padding

### ISSUE THREAD

**Issue by ror-shubham** [aeternity/aepp-blockchain-explorer#164]
child of #167
![image](https://user-images.githubusercontent.com/18702420/49434227-b7e4f700-f7d9-11e8-91a8-c47c9e1a1818.png)
 
![image](https://user-images.githubusercontent.com/18702420/49434286-dcd96a00-f7d9-11e8-8c4c-76d82847c61e.png)

**Comment by edwarddikgale** [comment]
Should be done on the whole application
