### ISSUE TITLE
Show the status transaction

### ISSUE THREAD

**Issue by edwarddikgale** [aeternity/aepp-blockchain-explorer#181]

**Comment by darioaschero** [comment]
![pending.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf5335d0912d30013fd0ee8/125516c66e82c728ace21e0d46f89194278b8daecda5fd53b652fa912a5265296b51a12d2287e079bd102a030b0d1bac42580d17fef9887aa7a42062c80d55b98e30063e937f03a6aa8317b500bf248f4e84beb8834ac1ec3b37aa.png)
![tx.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf5335d0912d30013fd0ee8/125516c66e82c728ace21e0d46fc8cd86fc093bb80e3ba40b01faad67c4421212b07f22922d4e12cbd472b525f0d1dae41590e45eee59b69f7e8682fd70541b8937f5566c7351badbd861bbe00b224824984b2be9801.png)
