### ISSUE TITLE
better UI/UX for prev/next gen navigation

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-blockchain-explorer#259]
currently this is very boring, no icon ect. Also its easy to overlook. It also doesn't really belong in the same box with the meta info of the generation IMHO.

If Design is ready or exists alread, please assign and link

**Comment by dadaphl** [comment]
![Screen Shot 2018-12-20 at 16.55.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf7dc201b09020011f85c41/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216456f36b7191a379e90c2e54415c46be5d4a1f06a3a3dc78e2a436628f0e5def833e5e26c43c43f8ead71fbc01e873894f84e7bd9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc5df549e04857a3143e64f43b.png)

**Comment by ror-shubham** [comment]
There are now buttons for this function.
http://localhost:8080/#/generation/26289
