### ISSUE TITLE
Allow tx_hashes in search field

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-blockchain-explorer#310]
For exampls: th_dZk2TeVF7NYuAwv19yEPkiyNswnG3S53WwHicxyvKFQPkFBL6 should lead to https://explorer.aepps.com/#/tx/th_dZk2TeVF7NYuAwv19yEPkiyNswnG3S53WwHicxyvKFQPkFBL6

As it states in the field description

**Comment by shekhar-shubhendu** [comment]
@emil-apeunit the search box already works that way.
we need to fix the error message here. the error message right now provided in the alert box is misleading and does not provide the correct reason for failure.

**Comment by ror-shubham** [comment]
The issue is fixed, and shows error `Connection to node is broken. Try again later.` if user tries to search before the connection is established.
