### ISSUE TITLE
Design: Transaction interval screen

### ISSUE THREAD

**Issue by ror-shubham** [aeternity/aepp-blockchain-explorer#317]
Child of #314
List transaction from generation to generation.
Explorer supported this in past.

**Comment by darioaschero** [comment]
![Generation Range.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bf5335d0912d30013fd0ee8/125516c66e82c728ace21e0d46cf9194269082bd86e6b103965cfe932c046b313916ac217586f76ae5002e03095d1cff400a5d45aeaddb7ea6b53c22d95e0bec806c4d68d47f40f2ecdd42e64bef62994597b7b5804dc5ec3b2de082874f3e1b0d109bb2.png)
