### ISSUE TITLE
Use middleware to get the number of transactions in a generation

### ISSUE THREAD

**Issue by ror-shubham** [aeternity/aepp-blockchain-explorer#331]
Child of #319

**Comment by kryztoval** [comment]
I came here exactly to ask for this, In a block with 84 micro blocks and 158 transactions it mkes a lot of calls before even showing the block information that it already has (like block height, microblock number and target.

![image](https://user-images.githubusercontent.com/5733028/50744300-a41d1e00-11e7-11e9-89c9-b47131c8c784.png)

This is by far too much, either transactions should be road asynchronously or loaded via the middleware

**Comment by ror-shubham** [comment]
https://github.com/aeternity/aepp-blockchain-explorer/commit/cd8243dd38760912e9f7f06526fece79cadc3743
