### ISSUE TITLE
Extract duplicate code in Transaction components

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-blockchain-explorer#49]
https://github.com/aeternity/aepp-blockchain-explorer/tree/499c71e/src/components/transaction
https://github.com/aeternity/aepp-blockchain-explorer/tree/499c71e/src/screens/transactionDetail

These components have the same structure and similar implementation. Should be possible to combine them in a single set of components to reduce code duplication and bundle size.

**Comment by davidyuk** [comment]
@edwarddikgale this is really solved or you are migrating issues to somewhere else?

**Comment by edwarddikgale** [comment]
There is a brand new development because we are re-doing this with new & updated design
