### ISSUE TITLE
Where do you find the transactions for an address?

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-blockchain-explorer#79]
Let's say I know this account has 71 mined blocks, ak_2TzcyaafoLpHaykzMbkrAXd8sFewbCZ2xFkBx5o1fMq1jbito

That means it should have 710,000,000,000,000,000 AE in the test network.

How do I see the transactions of an address? in etherscan.io is really simple, you just click on it, but on aepp-blockchain-explorer there are no transactions under the address.

**Comment by kryztoval** [comment]
I know you can see the transactions of a block, on http://localhost/#/generation/5573 for example,
but I was expecting to find it on the address details http://localhost/#/account/ak_Crxx1apEFv2WNKXHU9zok97iFbqM2soFkWM8dyj3KKzHeab3F

**Comment by ror-shubham** [comment]
Recently Epoch dropped endpoint for showing transactions for an account. We plan to introduce this again using a middleware between blockchain and apps. However, at present, there is no way to achieve this functionality.

**Comment by kryztoval** [comment]
That is sad. I hope we get this soon as this is important for the explorer.
