### ISSUE TITLE
Presentation error for big numbers under accounts balance in Chrome

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-blockchain-explorer#89]
## Expected Behavior
The balance should be correctly shown when asked via the rest interface
```
./aecli -u http://localhost:3013 -d http://localhost:3113 account balance wallet.ae
Enter the account password []:
<none>
  Balance ___________________________________________ 39999999999999994993
  Id ________________________________________________ ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg
7VpZsw7
  Nonce _____________________________________________ 4
</none>

```

## Actual Behavior
The balance gets rounded down to 39999999999999990000 due to numerical representation errors
http://explorer.tld:3013/v2/accounts/ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg7VpZsw7
```
{
"balance": 39999999999999994993,
"id": "ak_e8YApvLq9JyEWVg5KuyBo2gChWVwzD3g4oMHoVCSqg7VpZsw7",
"nonce": 4
}
```

## Steps to Reproduce the Problem
Set up a small network, mine a few blocks, get a humongous amount of balance, then check your balance on the aepp-blockchain-explorer.
  
## Logs, error output, etc.
 No pertaining configuration needed or error output obtained from browser

## Specifications
  - Virtualization: Docker
  - Node Version: 0.25.0

## Notes
I mined 4 blocks, at 10,000,000,000 AE per block. I registered 1 name and I spend 5000. the total should be  x4993 not x0000.

I started an issue on epoch because chrome was showing me the number rounded, but the API is returning the right number, which means the browser is rounding the number before showing it.
so now I am moving it here.

![image](https://user-images.githubusercontent.com/5733028/48592547-7cf44f80-e90e-11e8-8613-fd7120618df5.png)

Should we do string and treatment instead of showing it as a number to avoid presentation error?

The reference ticket is https://github.com/aeternity/epoch/issues/1770

**Comment by nduchak** [comment]
@kryztoval Hey, from sdk version 1.0.0 we will return balance as string with correct bignumber.

**Comment by kryztoval** [comment]
@nduchak sure, but the webpage is actually polling the node api directly.  I don't think this is done via the sdk right now on the explorer.

**Comment by nduchak** [comment]
What are you using for sent request's?(axios, fetch)

**Comment by kryztoval** [comment]
I am using aepp-blockchain-explorer@ca1d524266954073330b419fbbeb00f71220ffba with aepp-sdk-js@e7390221be06febbc0e1900a1e55cc93ee095111 with compatilibity updated to "1.0.0" instead.

you can see it live at http://criesca.com

**Comment by kryztoval** [comment]
http://criesca.com/#/generation/177 
http://criesca.com/#/account/ak_2df9FTmhbcQ1huwEBTV1s8WkJ9xhTb3eM6yn9pqopGj7bZmoXF
thouse ammounts seem correct


But this one... this one has this presentation error:
http://criesca.com/#/account/ak_26dopN3U2zgfJG4Ao4J4ZvLTf5mqr7WAgLAq6WxjxuSapZhQg5
![image](https://user-images.githubusercontent.com/5733028/49150013-3f5dd200-f2d1-11e8-8a24-8e0013817759.png)

**Comment by nduchak** [comment]
I see. That is relate to sdk. Sdk parse response using JSON.parse function which make this convertation of bignumber. So as i mentioned before we already change the parsing process in sdk. From version 1.0.0 we will return bignumber value as string.

**Comment by kryztoval** [comment]
Ok, I can't wait for the version 1.0.0 to be commited so I can try it out

**Comment by kryztoval** [comment]
![image](https://user-images.githubusercontent.com/5733028/49153303-f9a60700-f2da-11e8-9453-517fd65b2efb.png)
http://criesca.com/#/account/ak_26dopN3U2zgfJG4Ao4J4ZvLTf5mqr7WAgLAq6WxjxuSapZhQg5

Hey, it is looking a lot better :D

**Comment by nduchak** [comment]
Are you are using develop branch of sdk?

**Comment by kryztoval** [comment]
Yup :)

**Comment by nduchak** [comment]
Nice.:)

**Comment by kryztoval** [comment]
I did say I couldn't wait for it to be pushed! (=

**Comment by kryztoval** [comment]
On the same topic, are we gonna get localization? or at least something to differentiate integer and fractional values? I can't really remove 18 digits by eyesight :(

**Comment by nduchak** [comment]
I see. Good job!

**Comment by kryztoval** [comment]
I can almost close this one. Almost. 🗡

**Comment by kryztoval** [comment]
On the same topic, are we gonna get localization? or at least something to differentiate integer and fractional values? I can't really remove 18 digits by eyesight :(

**Comment by kryztoval** [comment]
https://github.com/aeternity/aepp-blockchain-explorer/commit/eed21e800348c24c7ba516dcf438b4556013553c

This commit shifts the values, great job!
